# ================================================================================================================================
#
#                                                              NAVI                                                           
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: grey # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 16 # column width relative to the terminal window
    min_width: 10 # minimum column width as number of characters
  comment:
    color: white
    width_percentage: 42
    min_width: 45
  snippet:
    color: white

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

# cheats:
  # path: /path/to/some/dir # equivalent to the --path option

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...
